"use strict";
const utils=require("@iobroker/adapter-core");
class AlarmControl extends utils.Adapter{
 constructor(options={}){super({...options,name:"alarm-control"});this.mode="disarmed";this.alarm=null;this.history=[];this.detectors=[];this.groups=[];this.areas=[];this.actions=[];this.subscriptions=new Map();this.timers=new Set();this.on("ready",()=>this.ready());this.on("stateChange",(id,state)=>this.change(id,state));this.on("unload",cb=>this.unload(cb));}
 arr(v,n){try{const x=typeof v==="string"?JSON.parse(v||"[]"):v;return Array.isArray(x)?x:[]}catch(e){this.log.error(`${n}: ${e.message}`);return[]}}
 async ready(){this.detectors=this.arr(this.config.detectors,"Melder").filter(x=>x&&x.enabled!==false&&x.id&&x.stateId);this.groups=this.arr(this.config.groups,"Meldegruppen").filter(x=>x&&x.enabled!==false&&x.id);this.areas=this.arr(this.config.areas,"Sicherungsbereiche").filter(x=>x&&x.enabled!==false&&x.id);this.actions=this.arr(this.config.actions,"Aktionen").filter(x=>x&&x.enabled!==false&&x.id);await this.objects();const m=await this.getStateAsync("status.mode");if(this.config.restoreModeAfterRestart&&m&&["disarmed","internal","external","vacation"].includes(m.val))this.mode=m.val;const h=await this.getStateAsync("status.history");try{this.history=JSON.parse(h?.val||"[]")}catch{}this.subscribeStates("control.*");for(const d of this.detectors){const a=this.subscriptions.get(d.stateId)||[];a.push(d);this.subscriptions.set(d.stateId,a);this.subscribeForeignStates(d.stateId)}if(this.config.residentsEnabled&&this.config.residentsStateId){this.subscribeForeignStates(this.config.residentsStateId);const s=await this.getForeignStateAsync(this.config.residentsStateId);if(s)await this.presence(s.val)}await this.setStateAsync("info.connection",true,true);await this.update();}
 async objects(){const defs=[["info.connection","Verbindung","boolean","indicator.connected",false],["status.mode","Alarmmodus","string","text",false],["status.modeText","Alarmmodus Text","string","text",false],["status.armed","Scharf","boolean","indicator",false],["status.alarm","Alarm aktiv","boolean","indicator.alarm",false],["status.alarmArea","Alarmbereich","string","text",false],["status.alarmGroup","Meldegruppe","string","text",false],["status.alarmDetector","Melder","string","text",false],["status.alarmTime","Alarmzeit","string","date",false],["status.presence","Anwesenheit","string","text",false],["status.openDetectors","Offene Melder","string","json",false],["status.history","Historie","string","json",false],["status.lastEvent","Letztes Ereignis","string","text",false],["status.lastError","Letzter Fehler","string","text",false],["control.armInternal","Intern scharf","boolean","button",true],["control.armExternal","Extern scharf","boolean","button",true],["control.armVacation","Urlaub scharf","boolean","button",true],["control.disarm","Unscharf","boolean","button",true],["control.reset","Alarm zurücksetzen","boolean","button",true],["control.panic","Panikalarm","boolean","button",true],["control.testAlarm","Testalarm","boolean","button",true],["control.silenceSiren","Sirene aus","boolean","button",true]];for(const [id,name,type,role,write] of defs)await this.setObjectNotExistsAsync(id,{type:"state",common:{name,type,role,read:true,write,def:type==="boolean"?false:""},native:{}})}
 async change(id,s){if(!s)return;if(id.startsWith(`${this.namespace}.control.`)&&!s.ack&&s.val===true){const c=id.split(".").pop();await this.setStateAsync(`control.${c}`,false,true);if(c==="armInternal")await this.arm("internal");if(c==="armExternal")await this.arm("external");if(c==="armVacation")await this.arm("vacation");if(c==="disarm")await this.disarm();if(c==="reset")await this.reset();if(c==="panic")await this.trigger({id:"panic",name:"Panikalarm"});if(c==="testAlarm")await this.trigger({id:"test",name:"Testalarm"},true);if(c==="silenceSiren")await this.silence();return}if(id===this.config.residentsStateId)return this.presence(s.val);for(const d of this.subscriptions.get(id)||[])await this.evaluate(d,s.val);await this.open();}
 values(v,csv){return String(csv||"").split(",").map(x=>x.trim().toLowerCase()).includes(String(v).toLowerCase())}
 async presence(v){let p="unknown";if(this.values(v,this.config.residentsHomeValues))p="home";else if(this.values(v,this.config.residentsVacationValues))p="vacation";else if(this.values(v,this.config.residentsAwayValues))p="away";await this.setStateAsync("status.presence",p,true);if(p==="home"&&this.config.autoDisarmHome)await this.disarm("Residents: anwesend");if(p==="away"&&this.config.autoArmAway&&this.mode==="disarmed")await this.arm("external","Residents: abwesend");if(p==="vacation"&&this.config.autoArmVacation)await this.arm("vacation","Residents: Urlaub")}
 activeGroups(mode){const s=new Set();for(const a of this.areas){const modes=Array.isArray(a.modes)?a.modes:String(a.modes||"").split(",").map(x=>x.trim());if(modes.includes(mode))for(const g of a.groupIds||[])s.add(g)}return s}
 compare(v,d){switch(d.condition||"true"){case"true":return v===true||v===1||v==="true";case"false":return v===false||v===0||v==="false";case"eq":return String(v)===String(d.value);case"neq":return String(v)!==String(d.value);case"gt":return Number(v)>Number(d.value);case"lt":return Number(v)<Number(d.value);case"between":return Number(v)>=Number(d.min)&&Number(v)<=Number(d.max);case"contains":return String(v).includes(String(d.value));case"regex":try{return new RegExp(String(d.value)).test(String(v))}catch{return false}default:return!!v}}
 armed(d){return d.alwaysActive===true||(this.mode!=="disarmed"&&this.activeGroups(this.mode).has(d.groupId))}
 async evaluate(d,v){if(!this.armed(d)||!this.compare(v,d))return;const sec=Math.max(0,Number(d.triggerDelaySeconds)||0);if(sec){const t=this.setTimeout(async()=>{const s=await this.getForeignStateAsync(d.stateId);if(s&&this.armed(d)&&this.compare(s.val,d))await this.trigger(d,false,s.val)},sec*1000);this.timers.add(t)}else await this.trigger(d,false,v)}
 async arm(mode,reason="Manuell scharf"){const open=await this.getOpen(mode);const block=open.filter(x=>(x.armBehavior||"block")==="block");if(block.length){await this.error(`Scharfschaltung verhindert: ${block.map(x=>x.name).join(", ")}`);return}this.mode=mode;await this.hist("armed",`${reason}: ${mode}`);await this.update()}
 async disarm(reason="Manuell unscharf"){this.mode="disarmed";await this.silence();await this.hist("disarmed",reason);await this.update()}
 async trigger(d,test=false,val=null){if(!test&&!this.armed(d))return;if(this.alarm&&!d.retrigger)return;const g=this.groups.find(x=>x.id===d.groupId);const a=this.areas.find(x=>(x.groupIds||[]).includes(d.groupId)&&((Array.isArray(x.modes)?x.modes:String(x.modes||"").split(",")).includes(this.mode)));this.alarm={detectorName:d.name||d.id,groupName:g?.name||"",areaName:a?.name||"",mode:this.mode,value:val,time:new Date().toISOString(),test};await this.hist(test?"test_alarm":"alarm",this.alarm.detectorName);await this.update();const ids=new Set([...(g?.actionIds||[]),...(a?.actionIds||[])]);if(d.id==="panic"||d.id==="test")for(const x of this.actions)ids.add(x.id);for(const id of ids){const x=this.actions.find(y=>y.id===id);if(x)await this.action(x)}}
 repl(t){const a=this.alarm||{};return String(t||"").replace(/\{(detector|group|area|mode|time|value)\}/g,(_,k)=>({detector:a.detectorName||"",group:a.groupName||"",area:a.areaName||"",mode:a.mode||this.mode,time:a.time||new Date().toISOString(),value:a.value??""}[k]))}
 cast(v,t){if(t==="boolean")return v===true||String(v).toLowerCase()==="true"||String(v)==="1";if(t==="number")return Number(v);if(t==="json")try{return JSON.parse(v)}catch{return v}return v}
 async action(a){try{const delay=Math.max(0,Number(a.delaySeconds)||0);if(delay){const t=this.setTimeout(()=>this.action({...a,delaySeconds:0}),delay*1000);this.timers.add(t);return}if(a.type==="telegram"){const p={text:this.repl(a.text||"ALARM: {detector} / {area}")};const u=a.user||this.config.telegramUser;if(u)p.user=u;this.sendTo(a.instance||this.config.telegramInstance,"send",p)}else if(a.type==="asterisk"){if((a.asteriskMode||this.config.asteriskMode)==="sendTo"){let p;try{p=JSON.parse(this.repl(a.payload||this.config.asteriskPayload))}catch{p=this.repl(a.payload||this.config.asteriskPayload)}this.sendTo(a.instance||this.config.asteriskInstance,a.command||this.config.asteriskCommand||"call",p)}else{const id=a.stateId||this.config.asteriskStateId;if(id)await this.setForeignStateAsync(id,this.cast(this.repl(a.value??"true"),a.valueType||"boolean"),false)}}else if(["state","siren","light","scene"].includes(a.type)&&a.stateId){await this.setForeignStateAsync(a.stateId,this.cast(this.repl(a.value??"true"),a.valueType||"boolean"),false);let sec=Number(a.offAfterSeconds)||0;if(a.type==="siren")sec=Math.min(sec||Number(this.config.maxSirenSeconds)||180,Number(this.config.maxSirenSeconds)||180);if(sec>0){const t=this.setTimeout(()=>this.setForeignStateAsync(a.stateId,this.cast(a.offValue??"false",a.valueType||"boolean"),false),sec*1000);this.timers.add(t)}}await this.hist("action",a.name||a.id)}catch(e){await this.error(`${a.name||a.id}: ${e.message}`)}}
 async silence(){for(const a of this.actions.filter(x=>x.type==="siren"&&x.stateId))try{await this.setForeignStateAsync(a.stateId,this.cast(a.offValue??"false",a.valueType||"boolean"),false)}catch(e){await this.error(e.message)}}
 async reset(){await this.silence();this.alarm=null;await this.hist("reset","Alarm zurückgesetzt");await this.update()}
 async getOpen(mode){const gs=this.activeGroups(mode);const r=[];for(const d of this.detectors){if(!gs.has(d.groupId)&&!d.alwaysActive)continue;const s=await this.getForeignStateAsync(d.stateId);if(s&&this.compare(s.val,d))r.push(d)}return r}
 async open(){const r=await this.getOpen(this.mode==="disarmed"?"external":this.mode);await this.setStateAsync("status.openDetectors",JSON.stringify(r.map(x=>({id:x.id,name:x.name,stateId:x.stateId}))),true)}
 async update(){await this.setStateAsync("status.mode",this.mode,true);await this.setStateAsync("status.modeText",this.alarm?"Alarm":({disarmed:"Unscharf",internal:"Intern scharf",external:"Extern scharf",vacation:"Urlaub"}[this.mode]||this.mode),true);await this.setStateAsync("status.armed",this.mode!=="disarmed",true);await this.setStateAsync("status.alarm",!!this.alarm,true);await this.setStateAsync("status.alarmArea",this.alarm?.areaName||"",true);await this.setStateAsync("status.alarmGroup",this.alarm?.groupName||"",true);await this.setStateAsync("status.alarmDetector",this.alarm?.detectorName||"",true);await this.setStateAsync("status.alarmTime",this.alarm?.time||"",true);await this.open()}
 async hist(type,message){const e={time:new Date().toISOString(),type,message};this.history.unshift(e);this.history=this.history.slice(0,Math.max(10,Number(this.config.historyLimit)||100));await this.setStateAsync("status.history",JSON.stringify(this.history),true);await this.setStateAsync("status.lastEvent",`${e.time} | ${type} | ${message}`,true)}
 async error(m){this.log.warn(m);await this.setStateAsync("status.lastError",m,true);await this.hist("error",m)}
 unload(cb){for(const t of this.timers)this.clearTimeout(t);this.setState("info.connection",false,true);cb()}}
if(require.main!==module)module.exports=o=>new AlarmControl(o);else new AlarmControl();
